version: '3.7'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "8080:80"
        container_name: project_nginx
        depends_on:
            - app

    pg:
        image: postgres:alpine
        restart: always
        env_file:
            -   .env
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            - DB_HOST=host.docker.internal
            - POSTGRES_DB=docker
            - POSTGRES_PASSWORD=root
        ports:
            - "8124:5432"
        container_name: project_db

    adminer:
        image: adminer
        restart: always
        ports:
            - "8088:8080"
        depends_on:
            - pg
        container_name: project_adminer

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www/
        user: 1000:1000
        depends_on:
            - pg
        container_name: project_app

